# -*- coding: utf-8 -*-
"""shivani.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6mhylEt2sY-TsRoe7X4rPnX0DX2dLZA
"""





"""multiplication of two numbers"""



a=10
b=5
c=a*b
print(c)





